mech/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import include
from django.conf.urls import patterns, url
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from django.conf import settings
from reg_backend.views import RegistrationViewUniqueEmail







urlpatterns = patterns('',
    (r'^statistic/',  include('training.urls', namespace='statistic')),
    (r'^video/',  include('videos.urls', namespace="video")),
    (r'^photologue/', include('photologue.urls')),


    (r'^admin/', include(admin.site.urls)),
    #url(r'^accounts/', include('registration.urls')),
    
    url(r'^register/$', RegistrationViewUniqueEmail.as_view(), name='registration_register'),
    #url(r'^register/complete/$',
    #                       TemplateView.as_view(template_name='registration/registration_complete.html'),
     #                      name='registration_complete'),
    
    url(r'^accounts/', include('registration.backends.default.urls')),

    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    #url(r'^logout/$', views.user_logout, {'next_page': '/'}),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),


    url(r'^', include('cms.urls')),
)






if settings.DEBUG:
    urlpatterns = patterns('',
                           
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),

    url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT, 'show_indexes': True}),     
                                  
    url(r'', include('django.contrib.staticfiles.urls')),
    
) + urlpatterns

training/urls.py
from django.conf.urls import patterns, url

from training import views



urlpatterns = patterns('',

    # ex: /photos/
    url(r'^$', views.ScoresView.as_view(), name='index'),
    url(r'^total_scores$', views.TotalScoresView.as_view(), name='total_scores'),
    
    url(r'^events$', views.EventsListView.as_view(), name='events'),
    url(r'^event/(?P<pk>\d+)$', views.EventDetailView.as_view(), name='event_detail'),
    # ex: /photos/5/
    #url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),

)

videos/urls.py
from django.conf.urls import patterns, url


import views





urlpatterns = patterns('',

    # ex: /
    url(r'^$', views.CategoryIndexView.as_view(), name='category_list'),
    
    #  /category/white
    url(r'^category/(?P<slug>[\-\d\w]+)$', views.CategoryDetailView.as_view(), name='category_detail'),
    url(r'^album/(?P<slug>[\-\d\w]+)$', views.AlbumDetailView.as_view(), name='album_detail'),
        





)

training/models.py
# -*- coding: utf-8 -*-


from django.db import models
from django.contrib.auth.models import User

#import pprint

import datetime
#from django.utils import timezone






class Event(models.Model):
    name =  models.CharField('Событие', max_length=100)

    date = models.DateField('Дата события')	#, auto_now_add=True
    #limit_choices_to = {'date__lte': datetime.date.today}

    class Meta:
        #name = ('event')
        verbose_name = ('соревнование(событие)')
        verbose_name_plural = ('соревнования(события)')
        ordering = ['date']
        permissions = (
            ("view_statistic", "Может просматривать статистику"),
        )

    

    def __unicode__(self):
        return self.name

    def users_count(self):
        return self.score_set.all().count()
    users_count.short_description = 'Кол-во участников'




class Score(models.Model):
    event = models.ForeignKey(Event)
    user = models.ForeignKey(User)
    score = models.SmallIntegerField('Баллы')
    comment = models.CharField('Коментарий', blank=True, max_length=100)
    
    
    
    #def __unicode__(self):
        #return `self.event_id` + ' - ' + `self.user_id` + ' - ' + `self.score`
    
    
    class Meta:
        verbose_name = ('результат')
        verbose_name_plural = ('результаты')
        unique_together = ("event", "user")
    
    
    
    

training/views.py
# -*- coding: utf-8 -*-
import json
import copy
from datetime import datetime, timedelta
from collections import OrderedDict

from django.views import generic
from django.db import connection, transaction
from django.contrib.auth.models import User

from training.models import Event, Score



def dictfetchall(cursor):
    "Returns all rows from a cursor as a dict"
    desc = cursor.description
    return [
        dict(zip([col[0] for col in desc], row))
        for row in cursor.fetchall()
    ]




class EventDetailView(generic.DetailView):
    model = Event
    template_name = 'training/event_detail.html'
    context_object_name = 'event'


class EventsListView(generic.ListView):
    context_object_name = 'latest_events'
    
    def get_queryset(self):
        """За последние полгода"""
        date_from = datetime.now() - timedelta(days=180)
        return Event.objects.order_by('date').filter(date__gt=date_from)



class ScoresView(generic.TemplateView):
    template_name = 'training/index.html'
    #context_object_name = 'latest_contests_list'

        
    def get_context_data(self, **kwargs):
        context = super(ScoresView, self).get_context_data(**kwargs)
       
        "Берём точку отсчёта(тренировку) после которой выводим остальные"
        now = datetime.now()
        date_from = datetime.now() - timedelta(days=180)
        events = Event.objects.order_by('date').filter(date__gt=date_from)
        
        dates = []
        events_order = OrderedDict()
        
        if not events:
            context['dates'] = '[]'
            context['series'] = '[]'
            return context

        i = 0;
        for e in events:
            dates.append(e.date.strftime("%d.%m.%Y"))
            events_order[e.id] = i
            i = i + 1

        cursor = connection.cursor()
        cursor.execute('''
            SELECT 
                --user_id,
                CONCAT(auth_user.last_name, ' ', auth_user.first_name) as name,
                GROUP_CONCAT(event_id) as events,
                GROUP_CONCAT(score) as scores
                
            FROM training_score
            LEFT JOIN auth_user ON (training_score.user_id = auth_user.id)
            WHERE auth_user.is_active AND training_score.event_id >= %(event_id)s
            
            GROUP BY user_id
                ''', {"event_id": events[0].id})
                    
       
        series = []
        for r in dictfetchall(cursor):
            events = r["events"].split(",")
            scores = r["scores"].split(",")
            events = map(int, events)
            scores = map(int, scores)
            
            scores = dict(zip(events, scores))
            data = []
            
            total_score = 0
            for ev_id, i in events_order.iteritems():
                if ev_id in scores:
                    total_score += scores[ev_id]
                    data.append([i, total_score])

        
            series.append({"name": r["name"], "data": data})
        

        context['dates'] = json.dumps(dates)
        context['series'] = json.dumps(series)
        return context
        
    
    
    
class TotalScoresView(generic.ListView):
    template_name = 'training/total_scores.html'
    context_object_name = 'users'
    
    def queryset(self, **kwargs):
        qs = User.objects.raw('''
            SELECT 
                auth_user.id,
                COUNT(training_score.id) as training_count,
                SUM(training_score.score) as total_scores
                
            FROM auth_user
            LEFT JOIN training_score ON (training_score.user_id = auth_user.id)
            WHERE auth_user.is_active
            
            GROUP BY user_id
            HAVING total_scores IS NOT NULL
            ORDER BY auth_user.last_name
                ''')

        return qs

    
    
    
    
    
'''
SELECT 
    user_id,
    GROUP_CONCAT(event_id) as events_ids,
    GROUP_CONCAT(score) as scores
FROM training_score

GROUP BY user_id



SELECT 
    user_id,
    auth_user.last_name, auth_user.first_name,
                
                GROUP_CONCAT(
                    CONCAT(event_id, ': ', score)
                ) as series,
                
    
    GROUP_CONCAT(event_id) as events,
    GROUP_CONCAT(score) as scores
    
FROM training_score
LEFT  JOIN auth_user ON (training_score.user_id = auth_user.id)
WHERE auth_user.is_active


GROUP BY user_id



'''
    
'''
SELECT 
    event_id,
    GROUP_CONCAT(user_id) as user_ids,
    GROUP_CONCAT(score) as scores
FROM training_score

GROUP BY event_id

'''
    
    
    
    
    

    

training/templates/training/event_detail.html
{% extends 'base.html' %}


{% block title %}Тренировка {{ event.name }}{% endblock %}

{% block base_content %}
	<h4>{{ event.name }} {{ event.date }}</h4>
	<br>
	
	
	<table class="table table-bordered table-hover table-condensed">
		<thead>
			<tr>
				<th>Участник</th>
				<th>Баллы</th>
				<th>Комментарий</th>
	
			</tr>
		</thead>
		<tbody>
			    {% for s in event.score_set.all %}
			        <tr>
			        	<td>{{ s.user.last_name }} {{ s.user.first_name }}</td>
			        	<td>{{ s.score }}</td>
						<td>{{ e.comment }}</td>
			        </tr>
			    {% endfor %}
		</tbody>
	</table>
	



{% endblock %}

training/templates/training/event_list.html
{% extends 'base.html' %}


{% block title %}Статистика - Тренировки{% endblock %}

{% block base_content %}





<div>
	<table class="table table-bordered table-hover table-condensed">
		<thead>
			<tr>
				<th>Тренировка</th>
				<th>Дата</th>
				<th>Кол-во участников</th>
	
			</tr>
		</thead>
		<tbody>
			    {% for e in latest_events %}
	
			        <tr>
			        	<td>
			        		<a href="{% url 'statistic:event_detail' e.id %}">{{ e.name }}</a>
			        	</td>
			        	<td>{{ e.date }}</td>
						<td>{{ e.users_count }}</td>
			        </tr>
			        
			    {% endfor %}
		</tbody>
	</table>
</div>

{% endblock %}

training/templates/training/index.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block title %}Статистика{% endblock %}


{% block base_content %}
	<a target="_blank" href="{% url 'statistic:events' %}">Тренировки</a>
	<a target="_blank" href="{% url 'statistic:total_scores' %}">Итоговые баллы</a>
	
	<br><br>
	<div id="container" style="min-width: 310px; height: 720px; margin: 0 auto"></div>




	<script>
	{% autoescape off %}
		dates = {{ dates }};
		series = {{ series }};
	{% endautoescape %}
	</script>
	<script src="{% static 'training/js/highcharts.js' %}" type="text/javascript"></script>
	<script src="{% static 'training/js/make_graph.js' %}" type="text/javascript"></script>

{% endblock %}

training/templates/training/index_bak.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load sekizai_tags %}



{% block base_content %}

<script src="{% static 'training/MilkChart/Assets/mootools-core-1.4.5.js' %}" type="text/javascript"></script>
<script src="{% static 'training/MilkChart/Assets/mootools-more-1.4.0.1.js' %}" type="text/javascript"></script>
<script src="{% static 'training/MilkChart/Source/MilkChart.yc.js' %}" type="text/javascript"></script>



<script src="{% static 'training/jquery.peity.min.js' %}" type="text/javascript"></script>

<table class="table table-bordered  table-hover table-condensed">
	<thead>
		<tr><th>Соревнования</th></tr>

		<tr>
			
			<th>Пользователь</th>
			<th>Рельзультат</th>

			<th>Дата события</th>

		</tr>
	</thead>
	<tbody>


		{% if latest_contests_list %}
		    {% for contest in latest_contests_list %}

		        <tr>
		        	<td>{{ contest.user_id }} - {{ contest.user }}</td>
		        	<td>{{ contest.result }}</td>
		        	<td>{{ contest.date }}</td>

		        	
		        </tr>
	        
		        
		    {% endfor %}
		{% else %}
	    	<tr><td>Нет данных соревнований</td></tr>
		{% endif %}



	</tbody>

</table>



<svg>
	<polyline points="0,0 50,0 150,100 250,100 300,150" fill="rgb(249,249,249)" stroke-width="1" stroke="rgb(0,0,0)"/>

	<polyline points="0,0 50,0 150,100 250,100 300,150" fill="rgb(100,100,100)" stroke-width="1" stroke="rgb(0,0,0)"/>

</svg>




<table id="chart">
    <thead>
        <tr>
            <th>Column A</th><th>Column B</th><th>Column C</th><th>Column D</th> 
        </tr>
    </thead>
    <tbody>
        <tr><td>8.3</td><td>70</td><td>10.3</td><td>100</td></tr>
        <tr><td>8.6</td><td>65</td><td>10.3</td><td>125</td></tr>
        <tr><td>8.8</td><td>63</td><td>10.2</td><td>106</td></tr>
        <tr><td>10.5</td><td>72</td><td>16.4</td><td>162</td></tr>
        <tr><td>11.1</td><td>80</td><td>22.6</td><td>89</td></tr>

    </tbody>
    <tfoot>
        <tr>
            <td>Row 1</td><td>Row 2</td><td>Row 3</td><td>Row 4</td><td>Row 5</td>
        </tr>
    </tfoot>
</table>



<span class="bar-colours-1">5,3,9,6,5,9,7,3,5,2</span>
<span class="bar-colours-2">5,3,2,-1,-3,-2,2,3,5,2</span>
<span class="bar-colours-3">0,-3,-6,-4,-5,-4,-7,-3,-5,-2</span>
<span class="pie-colours-1">4,7,6,5</span>
<span class="pie-colours-2">5,3,9,6,5</span>




<span class="line">5,3,9,6,5,9,7,3,5,2</span>
<span class="line">5,3,2,-1,-3,-2,2,3,5,2</span>
<span class="line">0,-3,-6,-4,-5,-4,-7,-3,-5,-2</span>





    {% addtoblock "js" %}
       <script>
			window.addEvent('domready', function() {
			    var chart = new MilkChart.Column("chart");
			})
				
				
				
				$("span.pie").peity("pie");
				
				$(".line").peity("line");
				
			</script>

		<script src="{% static 'training/jquery.peity.min.js' %}" type="text/javascript"></script>
		<script src="{% static 'training/MilkChart/Source/MilkChart.yc.js' %}" type="text/javascript"></script>
    {% endaddtoblock %}








{% endblock %}

training/templates/training/total_scores.html
{% extends 'base.html' %}


{% block title %}Итоговая статистика{% endblock %}

{% block base_content %}
	<h4>Итоговая статистика</h4><br>

	<table class="table table-bordered table-hover table-condensed">
		<thead>
			<tr>
				<th>Участник</th>
				<th>Кол-во тренировок</th>
				<th>Баллы</th>
				<th>Добавлен</th>
				<th>Дата последнего посещения сайта</th>
	
			</tr>
		</thead>
		<tbody>
			    {% for u in users %}
			        <tr>
			        	<td>{{ u.last_name }} {{ u.first_name }}</td>
			        	<td>{{ u.training_count }}</td>
			        	<td>{{ u.total_scores }}</td>
			        	<td>{{ u.date_joined|date:"Y-m-d"}}</td>
						<td>{{ u.last_login}}</td>
			        </tr>
			    {% endfor %}
		</tbody>
	</table>

{% endblock %}